### ISSUE TITLE
Is S3 Bubble dead?  What is going on?

### ISSUE THREAD

**Issue by Zetsunawa** [s3bubble/WordPress-Netflix-Style-Video-Streaming-Theme#118]
No updates on the theme, no responses to customer emails or support posts, forums seem dead.

I'd like to know if I need to migrate to a new platform.

**Comment by christianmilano** [comment]
for me too, no email support. did you find out something?

**Comment by s3bubble** [comment]
Hi Both, 

Apologies for the lack of support we have a big update planned for the end of October.

We are currently dealing with IP issues we have a company that has completely ripped of our theme and development and they are reselling it as their own.

We need to sort this out first because any updates we make here they just rip us of almost like we are building their service for them.

Beyond frustrating that people rip off other people’s work but something I suppose we have to deal with when having code on Github.

Best Regards

S3Bubble

**Comment by DrStupit** [comment]
Wow - Thats rough :( Hope you guys come right - This service is amazing

**Comment by Zetsunawa** [comment]
Thanks for the update.  Sorry about the IP issues and I hope they get resolved quickly and in your favor!
