### ISSUE TITLE
Add iframe, shortcode and themoviedb

### ISSUE THREAD

**Issue by freddiehdxd** [s3bubble/WordPress-Netflix-Style-Video-Streaming-Theme#48]
can you guys Add iframe, shortcode to add the movies, also add https://www.themoviedb.org/ api so we can add movies with one click

**Comment by leventmuslim** [comment]
Temporarily, _WP Movie Library_ should help until an enhancement arrives check the plugin repisotary [https://wordpress.org/plugins/wpmovielibrary/](url) 
I'm develeoping my website with it. Maybe you'd need to adjust custom post names in order to prevent any conflict if you're using S3Bubble's Streamium theme that's all
